export const clothes: {
  [name: string]: string[]
} = {
  Arlene: ["skirt", "tankTop"],
  Biker: [
    "armorLeatherGloves",
    "armorSwatHelmet",
    "facialPiercings",
    "gothBootsBlack",
    "gothicPants",
    "tankTop",
  ],
  Boe: ["denimPants", "dressShoes", "tshirt", "nerdGlasses"],
  Burnt: ["denimPants", "tshirt"],
  BusinessMan: ["cigar", "dressShoes", "shades", "suitJacket", "suitPants"],
  Cheerleader: ["hpRunningShoes", "runningShoes", "skirt", "tankTop"],
  Darlene: ["dressShoes", "shirt", "suitPants"],
  Farmer: ["cowboyBoots", "overalls", "sweatshirt"],
  FatCop: ["dressShoes", "suitJacket", "suitPants", "tshirt"],
  FatHawaiian: ["cigar", "dressShoes", "flannelShirt", "shades", "suitPants"],
  FemaleFat: ["skirt", "sweatshirt"],
  FootballPlayer: [
    "armorClothGloves",
    "armorClothPants",
    "armorFootballHelmetZU",
    "hpRunningShoes",
    "jacketLetter",
    "runningShoes",
  ],
  Joe: ["shirt", "denimShortsPants", "tshirt", "wornBoots", "nerdGlasses"],
  Lab: ["denimPants", "runningShoes", "shirt"],
  MaleHazmat: [
    "hazmatBoots",
    "hazmatGloves",
    "hazmatMask",
    "hazmatPants",
    "hazmatShirt",
  ],
  Marlene: ["denimPants", "runningShoes", "tankTop"],
  Moe: ["runningShoes", "denimShortsPants", "tankTop", "nerdGlasses"],
  Nurse: ["dressShoes", "skirt", "tankTop"],
  OldTimer: [
    "cowboyBoots",
    "cowboyHat",
    "denimPants",
    "leatherPoncho",
    "sweatshirt",
  ],
  Screamer: ["skirt", "sweatshirt"],
  Skateboarder: ["denimPants", "hoodedSweatshirt", "wornBoots"],
  Snow: [
    "denimPants",
    "flannelShirtRed",
    "hazmatGloves",
    "skullCap",
    "wornBoots",
  ],
  Soldier: [
    "armorMilitaryBoots",
    "armorMilitaryGloves",
    "armorMilitaryHelmet",
    "armorMilitaryLegs",
    "armorMilitaryVest",
    "armyPants",
    "armyShirt",
  ],
  Spider: ["tshirt", "denimPants"],
  Steve: ["denimPants"],
  Stripper: ["facialPiercings", "gothBootsBlack", "oldCash"],
  UtilityWorker: [
    "armorClothJacket",
    "armorMiningHelmet",
    "denimPants",
    "shirt",
    "wornBoots",
  ],
  Wight: [],
  Yo: ["cowboyBoots", "denimPants", "shirt"],
}

clothes.SteveCrawler = clothes.Steve
