export const items: { [name: string]: string[] } = {
  Arlene: [
    "drinkCanEmpty",
    "drinkJarEmpty",
    "foodCanBeef",
    "foodCanCatfood",
    "foodCanChicken",
    "foodCanChili",
    "foodCanDogfood",
    "foodCanHam",
    "foodCanLamb",
    "foodCanMiso",
    "foodCanPasta",
    "foodCanPears",
    "foodCanPeas",
    "foodCanSalmon",
    "foodCanSoup",
    "foodCanStock",
    "foodCanTuna",
    "foodCornMeal",
    "foodHoney",
    "toolCookingGrill",
    "toolCookingPot",
  ],
  Biker: [
    "ammo44MagnumBullet",
    "ammoGasCan",
    "gun44Magnum",
    "meleeClubIron",
    "meleeClubWood",
    "meleeToolHuntingKnife",
    "meleeToolMachete",
    "thrownAmmoMolotovCocktail",
  ],
  Boe: [
    "resourceDuctTape",
    "resourceFishingWeight",
    "resourceGlue",
    "resourceMetalPipe",
    "resourceNail",
    "resourceOil",
    "resourceScrapPolymers",
  ],
  Burnt: [
    "mineAirFilter",
    "mineCandyTin",
    "mineCookingPot",
    "mineHubcap",
    "resourceAirFilter",
    "resourceCandyTin",
    "resourceCoal",
    "resourceHubcap",
    "toolCookingPot",
  ],
  BusinessMan: [
    "casinoCoin",
    "oldCash",
    "resourceGoldNugget",
    "resourceRawDiamond",
    "resourceSilverNugget",
  ],
  Cheerleader: [
    "qc_blitzdefense",
    "qc_buythefarm",
    "qc_cableguysnevermadeit",
    "qc_dishonorabledischarge",
    "qc_dogdaysareover",
    "qc_dontfeedthebears",
    "qc_drunkanddisorderly",
    "qc_givemeaz",
    "qc_imalumberjackandimokay",
    "qc_itsbitsyspider",
    "qc_killthewabbit",
    "qc_ladykiller",
    "qc_maneater",
    "qc_nailsomechicks",
    "qc_nurseyoubacktohealth",
    "qc_silenceofthelambs",
    "qc_stagparty",
    "qc_starvingtourists",
    "qc_thatlldopig",
    "qc_yournothingspecial",
  ],
  Farmer: [
    "bucketEmpty",
    "drinkJarBeer",
    "meleeToolHoeIron",
    "meleeToolPaintTool",
    "plantedAloe1",
    "plantedBlueberry1",
    "plantedChrysanthemum1",
    "plantedCoffee1",
    "plantedCorn1",
    "plantedCotton1",
    "plantedGoldenrod1",
    "plantedMushroom1",
    "plantedPotato1",
    "plantedYucca1",
    "resourcePaint",
    "toolBellows",
    "treePlantedMountainPine1m",
    "treePlantedWinterPine1m",
  ],
  FatCop: ["ammoShotgunShell", "drinkCanMegaCrush", "gunPumpShotgun"],
  FatHawaiian: [
    "drinkJarGoldenRodTea",
    "drinkJarRedTea",
    "drinkJarSnowberryJuice",
    "drinkJarYuccaJuice",
    "drinkYuccaJuiceSmoothie",
    "meleeToolMachete",
  ],
  FemaleFat: [
    "foodBakedPotato",
    "foodBoiledMeat",
    "foodCharredMeat",
    "foodCornBread",
    "foodCornOnTheCob",
    "foodEggBoiled",
    "foodGrilledMeat",
    "foodHoboStew",
    "foodShamChowder",
  ],
  FootballPlayer: ["resourceScrapIron"],
  Joe: ["ammo9mmBullet", "gunPistol", "gunSMG5"],
  Lab: [
    "drinkJarGrainAlcohol",
    "drugAntibiotics",
    "drugFortBites",
    "drugPainkillers",
    "drugRecog",
    "drugSteroids",
    "drugSteroids",
    "drugVitamins",
    "medicalBandage",
    "medicalBloodBag",
    "medicalBloodDrawKit",
    "medicalFirstAidBandage",
    "medicalFirstAidKit",
    "medicalSplint",
    "toolBeaker",
  ],
  MaleHazmat: [
    "drugPainkillers",
    "drugVitamins",
    "qt_claude",
    "qt_jennifer",
    "qt_nickole",
    "qt_raphael",
    "qt_sarah",
    "qt_stephan",
    "qt_taylor",
  ],
  Nurse: [
    "drinkJarGrainAlcohol",
    "drugAntibiotics",
    "drugFortBites",
    "drugPainkillers",
    "drugRecog",
    "drugSteroids",
    "drugSteroids",
    "drugVitamins",
    "medicalBandage",
    "medicalBloodBag",
    "medicalBloodDrawKit",
    "medicalFirstAidBandage",
    "medicalFirstAidKit",
    "medicalSplint",
    "toolBeaker",
  ],
  OldTimer: [
    "ammo762mmBulletFMJ",
    "gunHuntingRifle",
    "meleeToolPickaxeIron",
    "meleeToolPickaxeSteel",
    "resourceBuckshot",
    "resourceBulletCasing",
    "resourceBulletTip",
    "resourceGoldNugget",
    "resourceGunPowder",
    "resourceRawDiamond",
    "resourceSilverNugget",
    "thrownDynamite",
  ],
  Screamer: [],
  Skateboarder: [
    "drinkJarBeer",
    "drugFortBites",
    "drugPainkillers",
    "drugRecog",
    "drugSteroids",
    "drugVitamins",
    "vehicleBicycleChassis",
    "vehicleBicycleHandlebars",
    "vehicleWheels",
  ],
  Snow: [
    "drinkJarCoffee",
    "meleeToolChainsaw",
    "meleeToolFireaxeIron",
    "meleeToolFireaxeSteel",
    "resourceSnowBall",
  ],
  Soldier: [
    "ammo762mmBulletFMJ",
    "ammoRocketFrag",
    "ammoRocketHE",
    "gunMR10",
    "gunRocketLauncher",
    "meleeToolHuntingKnife",
    "nightvisionGoggles",
    "thrownAmmoPipeBomb",
  ],
  Spider: ["resourceAcid", "resourceGlue"],
  Steve: ["medicalPlasterCast", "medicalSplint", "meleeToolAuger"],
  SteveCrawler: [
    "meleeToolAuger",
    "plantedAloe1",
    "plantedBlueberry1",
    "plantedChrysanthemum1",
    "plantedCoffee1",
    "plantedCorn1",
    "plantedCotton1",
    "plantedGoldenrod1",
    "plantedMushroom1",
    "plantedPotato1",
    "plantedYucca1",
    "treePlantedMountainPine1m",
    "treePlantedWinterPine1m",
  ],
  Stripper: ["oldCash"],
  UtilityWorker: [
    "gunToolNailgun",
    "meleeToolClawHammer",
    "meleeToolPaintTool",
    "meleeToolWrench",
    "resourceNail",
    "resourcePaint",
    "resourceRepairKit",
    "solarCell",
    "thrownDynamite",
    "toolAndDieSet",
  ],
  Wight: [
    "ammoCrossbowBoltExploding",
    "ammoCrossbowBoltIron",
    "ammoCrossbowBoltStone",
    "ammoCrossbowBoltSteelAP",
    "gunCrossbow",
    "meleeToolMachete",
  ],
}

items.Darlene = items.Arlene
items.Joe = items.Boe
items.Marlene = items.Arlene
items.Moe = items.Boe
items.Yo = items.OldTimer
