/**
 * A mod is disabled if
 * - it has not yet been ported to the latest version
 * - development is not finished
 * - other reasons I might not want to build and publish it
 */
export const distributedMods: string[] = [
  "AutoDestroyBirdsNest",
  // "AutoDestroyJunk",
  // "Bugs",
  // "ContainerDummies",
  // "ContainerSize",
  // "CorpseLifetime",
  // "CraftBoltsFromArrows",
  // "CraftConsumables",
  // "CraftEmptyCan",
  // "CraftJarFromBucket",
  // "CraftLight",
  // "CraftPaint",
  // "CraftSecureStorages",
  // "CraftWithForgedIron",
  // "CraftWithIron",
  // "CraftWithWood",
  // "DestroyPaintings",
  // "Dye",
  // "EngineQuality",
  // "HarvestAnimals",
  // "HarvestBirdNestsInTrees",
  // "HarvestChemistryStation",
  // "HarvestDoors",
  // "HarvestNuggets",
  // "HarvestPaletts",
  // "HarvestRock",
  // "HarvestTrees",
  // "LootAirDrop",
  // "LootAmmo",
  // "LootBirdNests",
  // "LootFoodAndWater",
  // "LootGuns",
  // "LootJunk",
  // "LootSportingGoods",
  // "LootWeaponMods",
  // "LootZombies",
  // "NoHoliday",
  // "PickStuffUp",
  // "PlayerDeathSickness",
  // "PlayerEncumbrance",
  // "PlayerStamina",
  // "QuestBasicSurvivalSkillPoints",
  // "RandomGen",
  // "RandomGenPreviewer",
  // "StackSize",
  // "StoragePocketModSlots",
  // "StrongerSecureStorages",
  // "ToolEntityDamage",
  // "ToolPowerSwingSound",
  // "ToolUpgrade+Repair",
  // "TradePricing",
  // "TradeVehiclesAndMore",
  // "UICompass",
  // "UICraftingQueue",
  // "UIFourDigitCraftAmount",
  // "UIGamestage",
  // "UIPlayerStatBars",
  // "UIScale",
  // "UIToolbelt",
  // "VehicleSpeed",
  // "WeaponCrossbowReloadTime",
  // "WeaponHeadshotDamage",
  // "WeaponSuppressorSound",
  // "XPForBlocks",
  // "XPForQuests",
  // "XPForZombies",
  "XPPlayerProgression",
  // "Zombie+Animal_Size+Range",
  // "Zombie+AnimalSpawning",
  // "ZombieBagDrop",
  // "ZombieBlockDamage",
  // "ZombieKnockdownDuration",
  // "ZombieWanderingHordeSize",
]
